name: AdminTrollMC
version: '${project.version}'
main: me.wcash.admintrollmc.AdminTrollMC
api-version: '1.21'
website: https://github.com/wyattduber/AdminTrollMC
author: Wcash
description: Admin Trolling Plugin

commands:
  atmc:
    description: Main AdminTrollMC command
    usage: /atmc (command) [arg1] [arg2]...
    permission: atmc.main
    permission-message: §c You don't have permission to use this command!

permissions:
  atmc.*:
    description: Gives access to all AdminTrollMC commands
    default: op
    children:
      atmc.reload: true
      atmc.main: true
      atmc.trolls.*: true
  atmc.main:
    description: Allows the use of the `/atmc` base command
    default: op
  atmc.reload:
    description: Allows use of the `/atmc reload` command
    default: op
  atmc.trolls.*:
    description: Gives access to all troll commands
    default: op
    children:
      atmc.blind: true
      atmc.burn: true
      atmc.chatsudo: true
      atmc.confuse: true
      atmc.deafen: true
      atmc.extinguish: true
      atmc.explode: true
      atmc.fakecrash: true
      atmc.fakedeop: true
      atmc.fakejoin: true
      atmc.fakeleave: true
      atmc.fakeop: true
      atmc.freeze: true
      atmc.jump: true
      atmc.unfreeze: true
  atmc.blind:
    description: Allows use of the `/atmc blind` command
    default: op
  atmc.burn:
    description: Allows use of the `/atmc burn` command
    default: op
  atmc.chatsudo:
    description: Allows use of the `/atmc chatsudo` command
    default: op
  atmc.confuse:
    description: Allows use of the `/atmc confuse` command
    default: op
  atmc.deafen:
    description: Allows use of the `/atmc deafen` command
    default: op
  atmc.extinguish:
    description: Allows use of the `/atmc extinguish` command
    default: op
  atmc.explode:
    description: Allows use of the `/atmc explode` command
    default: op
  atmc.fakecrash:
    description: Allows use of the `/atmc fakecrash` command
    default: op
  atmc.fakedeop:
    description: Allows use of the `/atmc fakedeop` command
    default: op
  atmc.fakejoin:
    description: Allows use of the `/atmc fakejoin` command
    default: op
  atmc.fakeleave:
    description: Allows use of the `/atmc fakejoin` command
    default: op
  atmc.fakeop:
    description: Allows use of the `/atmc fakeop` command
    default: op
  atmc.freeze:
    description: Allows use of the `/atmc freeze` command
    default: op
  atmc.jump:
    description: Allows use of the `/atmc jump` command
    default: op
  atmc.smite:
    description: Allows use of the `/atmc smite` command
    default: op
  atmc.unfreeze:
    description: Allows use of the `/atmc unfreeze` command
    default: op