name: AdminTrollMC
version: '${project.version}'
main: me.wcash.admintrollmc.AdminTrollMC
api-version: '1.20'
website: https://github.com/wyattduber/AdminTrollMC
author: Wcash
description: Admin Trolling Plugin

commands:
  atmc:
    description: Main AdminTrollMC command
    usage: /atmc (command) [arg1] [arg2]...
    permission: atmc.main
    permission-message: §c You don't have permission to use this command!

permissions:
  atmc.*:
    description: Gives access to all AdminTrollMC commands
    children:
      atmc.reload: true
      atmc.main: true
      atmc.fakecrash: true
  atmc.main:
    description: Allows the use of the `/atmc` base command
    default: op
  atmc.reload:
    description: Allows use of the `/atmc reload` command
    default: op
  atmc.fakecrash:
    description: Allows use of the `/atmc fakecrash` command
    default: op